trigger:
- main

pool:
  name: 'Pool'  # Replace 'AzureVM' with your self-hosted agent pool name

steps:

# Step 1: Install dependencies using pip
# Step 2: Run the Flask app
- script: |
    ipconfig
    systeminfo
    hostname
    tasklist
    python --version
    python app.py
  displayName: 'Run Flask app'
