trigger:
- main


pool:
  name: 'Pool'  # Replace 'Pool' with your self-hosted agent pool name

steps:
# Step 1: Install dependencies using pip
- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install Dependencies'

# Step 2: Run the Flask app
- script: |
    python app.py
  displayName: 'Run Flask App'
  env:  # Define environment variables here
    APP_ENV: 'Production'
    DEBUG_MODE: 'False'
