trigger:
- main

pool:
  name: 'AzureVM'  # Replace 'Default' with your self-hosted agent pool name

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Flask app'
