trigger:
- main

pool:
  name: 'AzureVM'  # Replace 'Default' with your self-hosted agent pool name

steps:

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Flask app'
