trigger:
- main

pool:
  name: 'AzureVM'  # Replace 'AzureVM' with your self-hosted agent pool name

steps:

# Step 1: Install dependencies using pip
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 2: Run the Flask app
- script: |
    python app.py
  displayName: 'Run Flask app'
